security:
  scriptApproval:
    approvedSignatures:
      - field jenkins.model.Jenkins clouds
      - method com.cloudbees.jenkins.plugins.amazonecs.ECSCloud setJenkinsUrl java.lang.String
      - method com.cloudbees.jenkins.plugins.amazonecs.ECSCloud setRegionName java.lang.String
      - method com.cloudbees.jenkins.plugins.amazonecs.ECSCloud setTemplates java.util.List
      - method com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate setLogDriver java.lang.String
      - method com.nirima.jenkins.plugins.docker.DockerTemplate setPullStrategy com.nirima.jenkins.plugins.docker.DockerImagePullStrategy
      - method hudson.model.Saveable save
      - method io.jenkins.docker.connector.DockerComputerJNLPConnector withUser java.lang.String
      - method java.util.Collection clear
      - method jenkins.model.Jenkins getExtensionList java.lang.Class
      - method jenkins.plugins.git.GitSCMSource setCredentialsId java.lang.String
      - method jenkins.scm.api.SCMSource setTraits java.util.List
      - method org.jenkinsci.plugins.workflow.libs.GlobalLibraries setLibraries java.util.List
      - method org.jenkinsci.plugins.workflow.libs.LibraryConfiguration setAllowVersionOverride boolean
      - method org.jenkinsci.plugins.workflow.libs.LibraryConfiguration setDefaultVersion java.lang.String
      - method org.jenkinsci.plugins.workflow.libs.LibraryConfiguration setImplicit boolean
      - method org.jenkinsci.plugins.workflow.libs.LibraryConfiguration setIncludeInChangesets boolean
      - new com.cloudbees.jenkins.plugins.amazonecs.ECSCloud java.lang.String java.lang.String java.lang.String
      - new com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String int int int java.lang.String java.lang.String boolean boolean java.lang.String java.util.List java.util.List java.util.List java.util.List java.util.List java.lang.String java.lang.String java.lang.String int
      - new com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate$EnvironmentEntry java.lang.String java.lang.String
      - new com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate$LogDriverOption java.lang.String java.lang.String
      - new com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate$MountPointEntry java.lang.String java.lang.String java.lang.String java.lang.Boolean
      - new com.nirima.jenkins.plugins.docker.DockerCloud java.lang.String java.util.List java.lang.String java.lang.String int int java.lang.String java.lang.String java.lang.String
      - new com.nirima.jenkins.plugins.docker.DockerTemplate com.nirima.jenkins.plugins.docker.DockerTemplateBase io.jenkins.docker.connector.DockerComputerConnector java.lang.String java.lang.String java.lang.String
      - new com.nirima.jenkins.plugins.docker.DockerTemplateBase java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String java.lang.Integer java.lang.Integer java.lang.Integer java.lang.Integer java.lang.String boolean boolean boolean java.lang.String java.lang.String
      - new hudson.slaves.JNLPLauncher
      - new io.jenkins.docker.connector.DockerComputerJNLPConnector hudson.slaves.JNLPLauncher
      - new java.io.File java.lang.String
      - new jenkins.plugins.git.GitSCMSource java.lang.String
      - new jenkins.plugins.git.traits.BranchDiscoveryTrait
      - new org.jenkinsci.plugins.workflow.libs.LibraryConfiguration java.lang.String org.jenkinsci.plugins.workflow.libs.LibraryRetriever
      - new org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever jenkins.scm.api.SCMSource
      - staticField com.nirima.jenkins.plugins.docker.DockerImagePullStrategy PULL_NEVER
      - staticMethod java.lang.System getenv java.lang.String
      - staticMethod jenkins.model.Jenkins getInstance
      - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods execute java.lang.String
      - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getText java.io.File
      - staticMethod org.codehaus.groovy.runtime.ProcessGroovyMethods getText java.lang.Process
      - method java.lang.Class getClassLoader
      - new groovy.lang.GroovyClassLoader groovy.lang.GroovyClassLoader
      - method groovy.lang.GroovyClassLoader parseClass java.io.File
      - method java.lang.Class newInstance
      - staticMethod java.util.logging.Logger getLogger java.lang.String
      - staticMethod com.amazonaws.regions.Regions getCurrentRegion
      - method com.amazonaws.regions.Region getName
      - staticMethod com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient builder
      - method SSMQuery getREGION
      - method com.amazonaws.client.builder.AwsClientBuilder withRegion java.lang.String
      - method com.amazonaws.client.builder.AwsClientBuilder build
      - method SSMQuery getParameterByName java.lang.Object
      - new com.amazonaws.services.simplesystemsmanagement.model.GetParameterRequest
      - method SSMQuery getLogger
      - method com.amazonaws.services.simplesystemsmanagement.model.GetParameterRequest withName java.lang.String
      - method com.amazonaws.services.simplesystemsmanagement.model.GetParameterRequest withWithDecryption java.lang.Boolean
      - method SSMQuery getAwsSimpleSystemsManagement
      - method com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagement getParameter com.amazonaws.services.simplesystemsmanagement.model.GetParameterRequest
      - method com.amazonaws.services.simplesystemsmanagement.model.GetParameterResult getParameter
      - method com.amazonaws.services.simplesystemsmanagement.model.Parameter getValue
      - new com.fasterxml.jackson.databind.ObjectMapper
      - method com.fasterxml.jackson.databind.ObjectMapper readTree java.lang.String
      - new java.util.HashMap
      - new com.fasterxml.jackson.core.type.TypeReference
      - method com.fasterxml.jackson.databind.ObjectMapper convertValue java.lang.Object com.fasterxml.jackson.core.type.TypeReference
      - method hudson.model.ItemGroup getAllItems java.lang.Class
      - method hudson.model.Item getFullName
      - staticMethod hudson.model.Hudson getInstance
      - method hudson.model.Hudson getJob java.lang.String
      - method jenkins.model.Jenkins getItemByFullName java.lang.String
      - new groovy.json.JsonBuilder java.lang.Object
      - method hudson.model.Job getLastBuild
      - method groovy.json.JsonBuilder toPrettyString
      - method SSMQuery putParameterOnPath java.lang.String java.lang.String java.lang.String boolean
      - new com.amazonaws.services.simplesystemsmanagement.model.PutParameterRequest
      - method com.amazonaws.services.simplesystemsmanagement.model.PutParameterRequest withName java.lang.String
      - method com.amazonaws.services.simplesystemsmanagement.model.PutParameterRequest withValue java.lang.String
      - method com.amazonaws.services.simplesystemsmanagement.model.PutParameterRequest withType java.lang.String
      - method com.amazonaws.services.simplesystemsmanagement.model.PutParameterRequest withOverwrite java.lang.Boolean
      - method com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagement putParameter com.amazonaws.services.simplesystemsmanagement.model.PutParameterRequest
      - method hudson.model.Run getNumber
      - method hudson.model.Job updateNextBuildNumber int
      - method hudson.model.Job getBuildByNumber int
      - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods toInteger java.lang.Number
      - new groovy.text.GStringTemplateEngine
      - method groovy.text.TemplateEngine createTemplate java.lang.String
      - method groovy.text.Template make java.util.Map
      - method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object
